services:
  jenkins:
    image: jenkins-go:latest #/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  ssh-agent:
    image: jenkins/ssh-agent

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ubuntu

  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /home/ubuntu/jenkinsgrafana/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=cbj
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=ubuntu
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=ubuntu

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
        #    depends_on:
        #- influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086

volumes:
  influxdb-storage:
  jenkins_home:
  grafana-storage:
  influxdb-storage:
