name: ppp

services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/18/data #/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres/data:/var/lib/postgresql/18/data  # Data directory
      - /data/postgres/config/postgresql.conf:/var/lib/postgresql/18/data/postgresql.conf
      - /data/postgres/config/pg_hba.conf:/var/lib/postgresql/18/data/pg_hba.conf

  jenkins:
    image: jenkins/jenkins:2.505-jdk21
    container_name: jenkins
    restart: always
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  ssh-agent:
    image: jenkins/ssh-agent

  grafana:
    image: grafana/grafana:11.4.0-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Expose Grafana on port 3000
    volumes:
      - /data/grafana:/var/lib/grafana # Persistent storage for Grafana data
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=Dupa123$ # Default admin password

  portainer:
    image: portainer/portainer-ce:2.27.1
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  portainer_agent:
    image: portainer/agent:2.27.1
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer_agent:/var/lib/docker/volumes
      - /:/host
